### ISSUE TITLE
suggestion loot

### ISSUE THREAD

**Issue by RIPISDRAD** [Slimefun-Addon-Community/Galactifun#100]
try giving players sth funny sth good !
u know after all of those tries there will be nothing there for example when u go to the moon there will be nothing there
not even the creepers(electrified) so if u can set a good loot for it

**Comment by Seggan** [comment]
the creepers *do* have good loot

**Comment by Seggan** [comment]
the moon dust is used for fusion reactors, and then there's the moon cheese

**Comment by RIPISDRAD** [comment]
well the creepers dont spawn
that an issue itself
