### ISSUE TITLE
[Enhancement] Set a max amount that Automatic doors can open (Configurable?)

### ISSUE THREAD

**Issue by Skizzles** [Slimefun-Addon-Community/Galactifun#101]
The Automatic Doors can have 64 blocks be automatic at once which I am not sure the amplifications of this if someone was to place say 100 of these or something.

Ideally, I would recommend having a set limit and optionally configurable.

https://screenshots.skizzles.me/wAnA3/mEyEwUWA49.mp4

**Comment by GallowsDove** [comment]
While I get what you mean, I think there are a LOT of ways to cause intentional lagging with slimefun, so I don't think anyone's gonna work on this anytime soon
