### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WongIong** [Slimefun-Addon-Community/Galactifun#105]
## Description (Required)
The plugin is disabled itself.

## Steps to reproduce the Issue (Required)
Starting the server

## Expected behavior (Required)
works

## Server Log / Error Report
https://pastebin.com/xFqzCrNh

## Environment (Required)

 - Minecraft Version: 
![image](https://user-images.githubusercontent.com/36799194/148075711-10e12f9b-3e50-4238-af27-4b414d8937c4.png)
 - Slimefun Version: 
![image](https://user-images.githubusercontent.com/36799194/148075735-1e10cdbb-e91b-4ddf-966a-7744d2b4c747.png)
![image](https://user-images.githubusercontent.com/36799194/148075677-2084a25c-646d-43c9-aec3-2dd0552bc4ef.png)
 - Plugin Version:

**Comment by WongIong** [comment]
It was working totally fine. but since two days ago it became this.

**Comment by Seggan** [comment]
You have 2 Galactifun installations. Remove one.

**Comment by WongIong** [comment]
No i have only one. But i did a reload with pluginsmanager
but this issue happens before i do the reload.

**Comment by WongIong** [comment]
The first disabled log is here https://pastebin.com/ttPXZHqD

**Comment by Seggan** [comment]
Update Galactifun

**Comment by Seggan** [comment]
Same as #106 which is fixed as of now. Further issues should be there

**Comment by WongIong** [comment]
Not gonna to open a new issue,
https://pastebin.com/2P97hDvQ
still a crash
