### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by WongIong** [Slimefun-Addon-Community/Galactifun#106]
## Description (Required)
It will crash the server

## Steps to reproduce the Issue (Required)
Start the server
wait 5 mins
It crashes the server

## Expected behavior (Required)
Make it works normally

## Server Log / Error Report
https://pastebin.com/fQbawJEH

## Environment (Required)

 - Minecraft Version:
![image](https://user-images.githubusercontent.com/36799194/148244422-4081fcea-edb2-4f3d-b50a-a9233c827763.png)
 - Slimefun Version:
![image](https://user-images.githubusercontent.com/36799194/148244445-0f61dfab-e97b-4793-ada0-1b236d5f013a.png)
 - Plugin Version: Dev-44

**Comment by Seggan** [comment]
Fixed once and for all (I actually tested this)
