### ISSUE TITLE
Can't make Space Grade Plate

### ISSUE THREAD

**Issue by Ironnoob73** [Slimefun-Addon-Community/Galactifun#115]
## Description (Required)
The recipe show that put Heavy Duty Sheet and Tungsten Carbide in Heated Pressure Chamber,but when I put them in the machine,the machine didn't do anything.

## Steps to reproduce the Issue (Required)
![2022-02-07_16.36.29.png](https://s2.loli.net/2022/02/07/VkqyF7Bobnt2NSz.png)
![2022-02-07_16.36.28.png](https://s2.loli.net/2022/02/07/jzK4yNxpQDnPwvB.png)
![2022-02-07_16.36.25.png](https://s2.loli.net/2022/02/07/VEKmLdQ6k4gMW3A.png)

## Expected behavior (Required)
The Heated Pressure Chamber should make Space Grade Plate .

## Environment (Required)
 - Minecraft Version:1.18.1(server) 1.17.1(client)
 - Slimefun Version:DEV - 999 (git e02eedd9)
 - Plugin Version:vDEV - 53 (git c2fc16bb)

**Comment by Boomer-1** [comment]
did you power it? not seeing any sign of power in your images

**Comment by Ironnoob73** [comment]
Yes,the shield blocks the wires.

> did you power it? not seeing any sign of power in your images

**Comment by Boomer-1** [comment]
there are no power wires in slimefun. are you referring to the energy connector?

**Comment by Ironnoob73** [comment]
> there are no power wires in slimefun. are you referring to the energy connector?

You must know what I means,I just don't know what its English name is......
The machine is properly connected to the grid and the other recipes work fine except this one.

**Comment by Seggan** [comment]
Ye that's a pressure chamber 2, you're using build 53, the fix is in build 56 or higher

**Comment by Ironnoob73** [comment]
Thanks.
