### ISSUE TITLE
Server Crash when Arriving or Having Players on Titan.

### ISSUE THREAD

**Issue by NickReagan** [Slimefun-Addon-Community/Galactifun#116]
Two players went to titan, the server crashed. Upon restart when those said players log back in the server crashes again.

## Expected behavior (Required)
Server don't crash.

[## Server Log / Error Report
https://pastebin.com/BrPfi8yB

## Environment (Required)

 - Minecraft Version: 1.17.1 - Paper #408
 - Slimefun Version: #999
 - Plugin Version: #58

**Comment by Seggan** [comment]
It is a Paper error, but the blame is still on me for not checking where I spawn my trees. I have already reported to Paper.
