### ISSUE TITLE
Stargate cannot be used to return to Earth

### ISSUE THREAD

**Issue by Ironnoob73** [Slimefun-Addon-Community/Galactifun#120]
## Description (Required)
I built stargates on Earth and in Earth orbit,I can get to Earth orbit through a stargate, but I can't get to Earth through a stargate.

## Steps to reproduce the Issue (Required)
Establish a stargate between the Earth and the Earth orbit, set the address of another stargate in the controller, enter the stargate on the Earth and come to the Earth orbit, and then cannot return to the Earth from the Earth orbit through the stargate.

## Expected behavior (Required)
Back to Earth from the Stargate.

## Environment (Required)
 - Minecraft Version:1.18.1(server) 1.17.1(client)
 - Slimefun Version:#999
 - Plugin Version: DEV 58 (git c9b57)

**Comment by Ironnoob73** [comment]
> You need to set the destination address of the Earth Orbit Stargate to the one on Earth. Links are one way.

I promise I set it.

**Comment by Ironnoob73** [comment]
> You need to set the destination address of the Earth Orbit Stargate to the one on Earth. Links are one way.

I have set each other's address for both stargates.

**Comment by Seggan** [comment]
Error logs?

**Comment by Ironnoob73** [comment]
> Error logs?

No, I am not the op, and the server owner seems unwilling to give out any server logs......

**Comment by Seggan** [comment]
Tell him that I cannot fix it without any error logs

**Comment by Ironnoob73** [comment]
Strangely, testing on my own local server doesn't have this problem.
Also, why can stargates only be built in the east-west direction?

**Comment by Ironnoob73** [comment]
And when I just went online, I found that the stargate on the earth lost its teleportation function (teleport me to the highest block of the y-axis where the stargate is located), and it needs to be closed and opened again to restore.

**Comment by Seggan** [comment]
Next time that happens, can you ask the owner to right click the stargate controller with a debug fish and send me the output?

**Comment by GallowsDove** [comment]
I'm going to have to close this because of a lack of information. If more information is provided, I'll open it again
