### ISSUE TITLE
Using explosive tools on some naturally generated Galactifun blocks duplicates them on the Moon and Mars

### ISSUE THREAD

**Issue by LordIdra** [Slimefun-Addon-Community/Galactifun#121]
## Description (Required)
Using either regular Explosive tools or Upgraded Explosive tools (from FluffyMachines) on any naturally generated block on the Moon or Mars will cause all the blocks apart from the one initially broken to remain in place while dropping an item. The break animation still plays, but the block remains in place. It does not appear to affect relics, and does not occur on any other worlds. One other person has mentioned this on the Discord but did not open an issue, and given the severity I would have assumed that someone would have mentioned it earlier, so I'm suspicious it may be a quirk of my environment. I've attached a plugins list in case this is useful for cross-referencing with any other reports.

## Steps to reproduce the Issue (Required)
Go to the Mars or the Moon and break a block using an explosive pickaxe. The central block should break and drop, and the surrounding blocks will drop but not break.

## Expected behavior (Required)
I expected the surrounding blocks to break along with dropping.

## Server Log / Error Report
No errors or any unusual messages in Slimefun/error-reports or server logs.

## Environment (Required)
![image](https://user-images.githubusercontent.com/35176119/156076580-0b339003-8d34-4a1b-92f0-a8cc1717f559.png)
![image](https://user-images.githubusercontent.com/35176119/156076640-0ec8a798-b10f-4555-abb3-d55cdf2224d0.png)
![image](https://user-images.githubusercontent.com/35176119/156076966-89e4a96f-d8cb-463c-a2fc-6dc4aa8d35d3.png)

 - Minecraft Version: 1.18.1
 - Slimefun Version: DEV - 999 (git e02eedd9)
 - Plugin Version: vDEV - 59 (git 871aec03)

**Comment by Seggan** [comment]
I will look into this, although I do not have much time recently
