### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by 100petr** [Slimefun-Addon-Community/Galactifun#124]
## Description (Required)

If the player selects the coordinates behind the border, he will lose the rocket
## Steps to reproduce the Issue (Required)

Set the border of the world
Teleport to coordinates beyond the border
The player dies (in my case, the player teleports to the frontier of the world (one of the purpur functional), but without the chest with rocket)
## Expected behavior (Required)

It would write a message to the player that he can only teleport to the coordinates of the border and it would write him the maximum coordinates, or if he wrote the coordinates behind the border, the plugin would automatically teleport him to the coordinates before the border with rocket in the chest.
## Server Log / Error Report

N/A
## Environment (Required)

 - Minecraft Version: 1.18.2
 - Slimefun Version: DEV 1009
 - Plugin Version: DEV 59

**Comment by 100petr** [comment]
Minor problem :D
![image](https://user-images.githubusercontent.com/29830635/164758513-3ff45053-e1ce-4f61-9c25-9e94905a0564.png)
![image](https://user-images.githubusercontent.com/29830635/164758613-8693845b-dbd2-4a9a-98ae-da1d7c139e6c.png)

**Comment by Seggan** [comment]
hmm is the border centered on 0,0?

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/164911082-03bd1394-e300-4815-a8ed-3a50afe06905.png)

**Comment by Seggan** [comment]
Fixed in latest
