### ISSUE TITLE
I hope the rocket device can go to more planets

### ISSUE THREAD

**Issue by wadigzxc** [Slimefun-Addon-Community/Galactifun#129]
## Steps to reproduce the Issue (Required)

![图片](https://user-images.githubusercontent.com/102936275/167285580-dd4a47c1-9b36-45cd-be20-a717831ae9df.png)
![图片](https://user-images.githubusercontent.com/102936275/167285593-535821f8-2b09-40e6-8148-69ef356fbce3.png)
![图片](https://user-images.githubusercontent.com/102936275/167285616-b35746bb-c48d-4d5b-9cca-cdfe7adde58d.png)

## Expected behavior (Required)
After starting the rocket launcher, it can only be transmitted to the end of the moon and the void, and other planets can't go.

## Environment (Required)

 - Minecraft Version:1.18.2
 - Slimefun Version:Slimefun-vf78c22a-canary.jar
 - Plugin Version:

**Comment by Boomer-1** [comment]
that's because you didn't discover them, or you didn't provide enough fuel

**Comment by Seggan** [comment]
the above ^^ (except you dont need to discover them)
