### ISSUE TITLE
Taking damage in sealed area with oxygen, heater, and cooler

### ISSUE THREAD

**Issue by JTechGaming** [Slimefun-Addon-Community/Galactifun#130]
## Description (Required)
Im in my base on mars, and im taking damage if i take my armor off in a sealed area, with a oxygen sealer, space heater tier 3, and cooling unit tier 3.

## Steps to reproduce the Issue (Required)
https://youtu.be/GWwV8FELXTM

I made a room, made out of sealable blocks, and placed space heaters, and cooling units, and a oxygen sealer. They are all operational, as displayed on their holograms. But sometimes you just randomly take damage, most of the time from being cold.

## Expected behavior (Required)
Take no damage, even without armor.

## Server Log / Error Report
There are no errors displayed.

## Environment (Required)
I play on a normal paper server on 1.18.2, with slimefun, and galactifun.
Plugin list:
https://pastebin.com/DJM7sCCu

 - Minecraft Version:
 git-Paper-276 (MC 1.18.2)
 - Slimefun Version:
 Slimefun4 - DEV 1008 (git 02009)
 - Plugin Version: 
 Galactifun - DEV 61 (git 51e87)

**Comment by Seggan** [comment]
I meant add your info to #68
