### ISSUE TITLE
Error (i dunno what, "they" just told me to post here) MC 1.19.3

### ISSUE THREAD

**Issue by TheExotik** [Slimefun-Addon-Community/Galactifun#141]
[2023-02-23-21-08.txt](https://github.com/Slimefun-Addon-Community/Galactifun/files/10819677/2023-02-23-21-08.txt)

**Comment by TheExotik** [comment]
this is a message error saved in slimefun error-reports

**Comment by Seggan** [comment]
This is a blockstorage issue. Slimefun related, not Galactifun.
