### ISSUE TITLE
Hard Crash

### ISSUE THREAD

**Issue by Indistoupia** [Slimefun-Addon-Community/Galactifun#157]
## Description 
I was playing in my world, i tried the galactifun, till i get into the world earth_orbit, i travel around but the game crashes

## Steps to reproduce the Issue
- tp to earth orbit
- travel some chunks
- get crash

## Expected behavior 
the game not crash

## Server Log / Error Report
https://mclo.gs/6n5zh7k

## Environment

 - Minecraft Version: paper 1.20.1 build 196
 - Slimefun Version: slimefun rc 36
 - Plugin Version:  galactifun 76

## Just in case
I tried entering again to my server, and now i can generate terrain without crashes

**Comment by JustAHuman-xD** [comment]
Shouldn't use sf release candidate firstly

**Comment by JustAHuman-xD** [comment]
Looks like it's caused by:
`Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 3
	at io.github.addoncommunity.galactifun.util.Sphere.gen(Sphere.java:137) ~ `

**Comment by Seggan** [comment]
dupe of #151
