### ISSUE TITLE
Circuit Presser not Working

### ISSUE THREAD

**Issue by alfonsusac** [Slimefun-Addon-Community/Galactifun#56]
## Description (Required)
Circuit presser not pressing any blocks.
Tried it with: Lapiz, Redstone, Diamond, and Glowstone.

## Steps to reproduce the Issue (Required)
1. Place down circuit presser
2. Insert any of the blocks 
![image](https://user-images.githubusercontent.com/20208219/132938990-2525747d-b714-4f98-b212-48c85e2d1d86.png)

## Expected behavior (Required)
Circuit would be presed.

## Server Log / Error Report
No Error Log

## Environment (Required)
![image](https://user-images.githubusercontent.com/20208219/132938986-9d1d527e-f265-437e-a4cd-a63bec39c5fd.png)

**Comment by Seggan** [comment]
You need silicon along with it
