### ISSUE TITLE
Space Suit Upgrades

### ISSUE THREAD

**Issue by alfonsusac** [Slimefun-Addon-Community/Galactifun#57]
## Description (Required)
For some reason, space suits pants are able to be upgraded wiht radiation resistance **twice** while other space suits only allows one type of upgrade

## Steps to reproduce the Issue (Required)
1. Put down space suit upgrader
2. Put space suit pants in the left side of the blue box
3. Put Radiation Resistance Upgrade on the right side of the blue box
4. Put the space suit pants on the orange box back to the blue box.
![image](https://user-images.githubusercontent.com/20208219/132939378-8c9edab1-cad0-4737-816f-7df4423b971c.png)

## Expected behavior (Required)
I dont know? depends on the design, perhaps make it into Radiation Resistance II or be conssitent with only allowing one type of upgrade.

## Server Log / Error Report
No Error Report

## Environment (Required)
![image](https://user-images.githubusercontent.com/20208219/132939360-b4510706-2e8d-458a-bbc6-abfe3f0a5b30.png)

**Comment by Seggan** [comment]
@Mooy1 you designed this, can you confirm if it's intentional or not?

**Comment by Mooy1** [comment]
Its intentional, the pants have 2 upgrade slots

**Comment by YOnikos** [comment]
Can't updrade armor
