### ISSUE TITLE
Keep inventory isn’t working on planets

### ISSUE THREAD

**Issue by ashton1200** [Slimefun-Addon-Community/Galactifun#58]
## Description (Required)
When your on a new planet it doesn’t seem to use keep inventory even if it’s on (unsure if fixed this was on first version)

## Steps to reproduce the Issue (Required)
Turn on keep inventory go to the moon and /kill

## Expected behavior (Required)
Keep inventory works

## Environment (Required)

![CD487F91-81F7-4E60-8342-369C0F020907](https://user-images.githubusercontent.com/64140445/132953817-714dd905-9e8c-47a4-b039-8c441cefafa9.jpeg)
![56EBB97B-1C11-471A-9F9D-ECCCD6791E15](https://user-images.githubusercontent.com/64140445/132953820-95dc64ce-4d02-445b-9070-747d8a37c4b9.jpeg)

 - Minecraft Version: 1.17.1
 - Slimefun Version: look at screenshot
 - Plugin Version: look at screenshot

**Comment by Flymetothemoon25** [comment]
it has a old version of claytech and other addons... Might be worth checking if this changes anything since it could be a claytech generated plannet/world

**Comment by Seggan** [comment]
use `/galactifun worrld world_galactifun_the_moon` to make sure you're on the galactifun moon. and galactifun has a lot of incompatibility issues with claytech, remove it first

**Comment by ashton1200** [comment]
Alright will do I’ll also fill my inventory with junk for a recording

**Comment by ashton1200** [comment]
Can’t do it at the moment will do it later

**Comment by Seggan** [comment]
I can't reproduce. I did you steps and it kept my inventory

**Comment by ashton1200** [comment]
Say alright it was probably fixed then

**Comment by ashton1200** [comment]
oop sorry

**Comment by ashton1200** [comment]
So used to typing “say” before a message I’m someone so used to console lol
