### ISSUE TITLE
You die in void if you say unsafe location on Earth Orbits

### ISSUE THREAD

**Issue by TerslenK** [Slimefun-Addon-Community/Galactifun#62]
## Description (Required)
When you go to "Earth Orbits" if your coordinates isnt on a block, you will fall to void

## Steps to reproduce the Issue (Required)
simply create rocket multiblock then select Earth Orbits 
## Expected behavior (Required)
When you say unsafe location, it could teleport you to nearest safe location

## Server Log / Error Report
no error or log

## Environment (Required)

 - Minecraft Version: 1.17-1.17.1
 - Slimefun Version: DEV - #968
 - Plugin Version:  Galactifun build 5

**Comment by Seggan** [comment]
Intended feature. Will mark as enhancement

**Comment by Lennywasafish** [comment]
> Intended feature. Will mark as enhancement

If it's intended, how are you supposed to choose a location without knowing whether or not you're going to die?

**Comment by Seggan** [comment]
It's kinda a guessing game. Shouldn't the chest that generates keep you from falling?

**Comment by Lennywasafish** [comment]
> It's kinda a guessing game. Shouldn't the chest that generates keep you from falling?

It should but it doesnt
