### ISSUE TITLE
Nose Cone drops redstone torch when broken by water

### ISSUE THREAD

**Issue by GallowsDove** [Slimefun-Addon-Community/Galactifun#63]
## Description (Required)

Nose Cone should be non-placeable to avoid issues such as dropping regular redstone torch when broken by water, or 

## Steps to reproduce the Issue (Required)

Break a Nose Cone by water.

## Expected behavior (Required)

Either drop a Nose Cone or to be non-placeable

## Server Log / Error Report

None

## Environment (Required)

Dev test server with latest version, trust me bro.

**Comment by Mooy1** [comment]
I think we can make it use UnplaceableBlock to fix this
