### ISSUE TITLE
Circuit Press

### ISSUE THREAD

**Issue by RafaelZNTD** [Slimefun-Addon-Community/Galactifun#70]
## Description (Required)
When you put some Circuit press on the ground, this happens: https://pastebin.com/pHDJu1V9

 - Minecraft Version: 1.17.1 - Paper 257
 - Slimefun Version: DEV 968
 - Plugin Version: vDEV 7

**Comment by Seggan** [comment]
See Discord, that doesn't seem to be the full report

**Comment by RafaelZNTD** [comment]
https://pastebin.com/zmRgEx5b 
not all files seems to be with the error... i think this is right now

**Comment by Seggan** [comment]
Noooooo

**Comment by RafaelZNTD** [comment]
Idk what happens, hope u can fix that kkkk
