### ISSUE TITLE
Rocket launching without taking the players with it

### ISSUE THREAD

**Issue by bryanhhh** [Slimefun-Addon-Community/Galactifun#74]
## Description (Required)

After setting up the rocket with its launchpad, you choose the destination and you type in the coordinates.
Then after 5 messages, it should bring any entities within 5 blocks to the destination.
But unless you're not OP, the rocket doesn't bring you to the destination.

So I think there may be some tweaking to do on your end since there are only Slimefun and Galactifun installed

## Steps to reproduce the Issue (Required)
Download papermc 1.17.1 and set up local server
Install just Slimefun and Galactifun

## Expected behavior (Required)
Bring the players with it to the destination

## Server Log / Error Report

Only errors I see is here but I believe this is from due to hosting from local and has no issue with running Slimefun
https://pastebin.com/DyEWcYTN

## Environment (Required)

![Screenshot 2021-09-24 183335](https://user-images.githubusercontent.com/21322684/134742039-526c347c-4c41-4c74-9cd8-e698a7d4bb5b.png)

**Comment by zimzaza4** [comment]
Hey I think I know the problem
