### ISSUE TITLE
[Major] Unable to change world name

### ISSUE THREAD

**Issue by TheRealM18** [Slimefun-Addon-Community/Galactifun#75]
## Description (Required)
When trying to identify that the world would be called "Main", it will not accept it.  We use all our servers with the name set to Main not world. This includes the capital of "Main", not just "main".

## Steps to reproduce the Issue (Required)
Set "earth-name: world" to "earth-name: Main"

## Expected behavior (Required)
This should work, as it is an option.

## Environment (Required)
 - Java: 16
 - Server Type: paper-1.17.1-287
 - Minecraft Version: 1.17.1
 - Slimefun Version: DEV 975 (git e2d2e)
 - Plugin Version: DEV 13 (git 85bd8)

**Comment by Seggan** [comment]
What do you mean "it doesn't work"? How do you know it doesn't work?

**Comment by TheRealM18** [comment]
![image](https://user-images.githubusercontent.com/5025664/135521295-b1fd0dfd-31f6-4b96-bb39-7ba70b310c76.png)

**Comment by Seggan** [comment]
Do you mean that the planets all start with "world"?

**Comment by TheRealM18** [comment]
I guess if it is the first time you change it, it doesnt work, but the second time you load the server with the new setting I guess it does

**Comment by Seggan** [comment]
> Do you mean that the planets all start with "world"?

Please answer my question

**Comment by TheRealM18** [comment]
it was also a concern of mine, but it did make a "world" folder, and was wondering why.

**Comment by Seggan** [comment]
Yes, `world` will be created if it is set as the Earth world. It will *not* be created if the Earth world name exists. As for all the planets starting with "world_", that is intentional and does not affect gameplay
