### ISSUE TITLE
Error occurred while enabling Galactifun vDEV - 13

### ISSUE THREAD

**Issue by ErythroCraft** [Slimefun-Addon-Community/Galactifun#76]
## Description (Required)##
I istalled GalactiFun and was wondering about this error
(Startup error)

## Steps to reproduce the Issue (Required)##
1. installing GalactiFun
2. starting server

## Expected behavior (Required)##

 - Minecraft Server Version: 3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
 - Slimefun Version: Slimefun vDEV - 975 (git e2d2ec60)
 - Plugin Version: Galactifun vDEV - 13 (git 85bd8f5d)
 

[latest.log](https://github.com/Slimefun-Addon-Community/Galactifun/files/7267441/latest.log)

**Comment by Seggan** [comment]
Galactifun requires Paper or a fork of Paper
