### ISSUE TITLE
Automatic Door - Issues

### ISSUE THREAD

**Issue by AN0NISN4P** [Slimefun-Addon-Community/Galactifun#78]
Hey! I've been playing around with the Automatic Door recently and found some issues, so I thought it'd be easiest to just mention them all here at once.

# 1: Unobtainable Blocks
## Description
It is possible for players, using the Automatic Door to get unobtainable blocks, examples would be Bedrock or Budding Amethyst. Basically any block which has been placed down in the world can be picked up using just the Automatic Door and piece of Dirt.

## How to
The way you'd do it, is place the Automatic Door up against the block you want to pick up _([Example](https://gyazo.com/e1e6932d316f669738b8bc044ff9d80f))_ and then add the Dirt block to it's inventory. Then as you walk away, the door will attempt to place the Dirt block and fail, but it'll still see itself as having closed the door. If you then walk a bit closer to it, so you just barely can reach it, and remove the Dirt from the Inventory, when walking up to the door it will open and have the block (bedrock) inside.
- Place Automatic Door on Unobtainable block
- Put random block inside Automatic Door
- Walk away
- Go just barely close enough to reach the door
- Remove random block
- Walk closer
- Profit (?)

## Expected Behaviour
It'd be expected the Automatic Door just does nothing.

## My suggestion
As the issue is right now, it's mostly a case of the Door picking up blocks which it didn't place, that would indeed solve the issue of getting the unobtainable blocks to begin with. But on top of that, I'd say maybe consider having a list in config for blocks the door should not be able to pick up, with stuff like Bedrock being a default value in it. This will allow people to still do it if the server owner permits it, but will also fix the problem entirely

<hr>

# 2: Block not dropping

## Description
This one is a little harder to explain, as I have no clue what could be causing this. But it is just the Item does not always drop when broken. At times after breaking the Automatic Door it's refused to drop as an item. Just completely vanished. Checking with CoreProtect it shows as the block having been broken, but the item just never dropped. The only thing I believe could cause this would be insta breaking the block. But I've never experienced this happening with any other SF machine, neither from the base Slimefun 4, or from any of the addons I've played with.

## Steps to reproduce the Issue
It happens fairly randomly and I've not found any consistent ways of getting it to occur
- Place Automatic Door
- Break Automatic Door
- Hope for the best

## Expected behavior
The Item form would be expected to drop every single time, and it does, most of the time. Just every now and again, it doesn't drop.

<hr>

# 3: Infinite Cake

## Description
The Automatic Door picks up half eaten cake, and spits out fresh new cake. Infinite food

## How to
- Place Automatic Door
- Put Cake inside
- Step back
- _Door places cake_
- Eat a piece of cake
- Step closer
- _Door removes cake_
- Now repeat

## Expected behavior
The cake shouldn't be pulled back when it's had a bite taken out of it...

<hr>

## Environment
All of this has been noticed on the same server on these versions.
Server / Slimefun 4 version : [gyazo](https://gyazo.com/b0ef59bf2f47818e8f1ca86d0c093be6)
Addon Version : [gyazo](https://gyazo.com/ccbd9fb7f3ea1ea9440fd3d6dbc1e4b9)

**Comment by Seggan** [comment]
Please split these up into 3 reports so we can manage each separately.
