### ISSUE TITLE
Unobtainable Blocks

### ISSUE THREAD

**Issue by AN0NISN4P** [Slimefun-Addon-Community/Galactifun#79]
## Description
It is possible for players, using the Automatic Door to get unobtainable blocks, examples would be Bedrock or Budding Amethyst. Basically any block which has been placed down in the world can be picked up using just the Automatic Door and piece of Dirt.

## How to
The way you'd do it, is place the Automatic Door up against the block you want to pick up _([Example](https://gyazo.com/e1e6932d316f669738b8bc044ff9d80f))_ and then add the Dirt block to it's inventory. Then as you walk away, the door will attempt to place the Dirt block and fail, but it'll still see itself as having closed the door. If you then walk a bit closer to it, so you just barely can reach it, and remove the Dirt from the Inventory, when walking up to the door it will open and have the block (bedrock) inside.
- Place Automatic Door on Unobtainable block
- Put random block inside Automatic Door
- Walk away
- Go just barely close enough to reach the door
- Remove random block
- Walk closer
- Profit (?)

## Expected Behaviour
It'd be expected the Automatic Door just does nothing.

## My suggestion
As the issue is right now, it's mostly a case of the Door picking up blocks which it didn't place, that would indeed solve the issue of getting the unobtainable blocks to begin with. But on top of that, I'd say maybe consider having a list in config for blocks the door should not be able to pick up, with stuff like Bedrock being a default value in it. This will allow people to still do it if the server owner permits it, but will also fix the problem entirely

## Environment
Server / Slimefun 4 version : [gyazo](https://gyazo.com/b0ef59bf2f47818e8f1ca86d0c093be6)
Addon Version : [gyazo](https://gyazo.com/ccbd9fb7f3ea1ea9440fd3d6dbc1e4b9)

**Comment by Seggan** [comment]
Fixed
