### ISSUE TITLE
Automatic Door not Dropping

### ISSUE THREAD

**Issue by anonisnap** [Slimefun-Addon-Community/Galactifun#80]
## Description
At times when breaking the Automatic Door, it refuses to drop as an item. Just completely vanishing. Checking with CoreProtect it shows as the block having been broken, but the item didn't drop. The only thing I believe could cause this would be insta breaking the block. But I've never experienced this happening with any other SF machine, neither from the base Slimefun 4, or from any of the addons I've played with.

## Steps to reproduce the Issue
It happens fairly randomly and I've not found any consistent ways of getting it to occur
- Place Automatic Door
- Break Automatic Door
- Hope for the best

## Expected behavior
The Item form would be expected to drop every single time, and it does, most of the time. Just every now and again, it doesn't drop.

## Environment
Server / Slimefun 4 version : [gyazo](https://gyazo.com/b0ef59bf2f47818e8f1ca86d0c093be6)
Addon Version : [gyazo](https://gyazo.com/ccbd9fb7f3ea1ea9440fd3d6dbc1e4b9)

**Comment by zimzaza4** [comment]
This is randomly ... it is difficult to find the problem.

**Comment by GallowsDove** [comment]
I've tried to recreate this in both creative and survival, with various tools and not one has disappeared. Unless we can find a consistent way to reproduce this, I'm gonna have to assume that you've just lost it somewhere.
