### ISSUE TITLE
Infinite Cake

### ISSUE THREAD

**Issue by AN0NISN4P** [Slimefun-Addon-Community/Galactifun#81]
## Description
The Automatic Door picks up half eaten cake, and spits out fresh new cake. Infinite food

## How to
- Place Automatic Door
- Put Cake inside
- Step back
- _Door places cake_
- Eat a piece of cake
- Step closer
- _Door removes cake_
- Now repeat

## Expected behavior
The cake shouldn't be pulled back when it's had a bite taken out of it...

## Environment
Server / Slimefun 4 version : [gyazo](https://gyazo.com/b0ef59bf2f47818e8f1ca86d0c093be6)
Addon Version : [gyazo](https://gyazo.com/ccbd9fb7f3ea1ea9440fd3d6dbc1e4b9)

**Comment by Seggan** [comment]
Fixed

**Comment by zimzaza4** [comment]
Remember to replace your config.yml
https://github.com/Slimefun-Addon-Community/Galactifun/blob/master/src/main/resources/config.yml

**Comment by Seggan** [comment]
it will auto generate. infinitylib stuff :)
