### ISSUE TITLE
Diamond anvil disappears

### ISSUE THREAD

**Issue by zimzaza4** [Slimefun-Addon-Community/Galactifun#82]
## Description (Required)

Diamond anvil disappears immediately after placing, and leave an error log
## Steps to reproduce the Issue (Required)

Place diamond anvil
## Expected behavior (Required)

It should not disappear
## Server Log / Error Report

https://pastebin.com/x9M6iSe6
## Environment (Required)

 - Minecraft Version: 1.17.1
 - Slimefun Version: Slimefun DEV - 976 (git fe9d11d8)
 - Plugin Version: ALPHA

**Comment by Seggan** [comment]
please use latest, not alpha

**Comment by zimzaza4** [comment]
ummm...

**Comment by Seggan** [comment]
latest is on builds server, i think its build 13 by now

**Comment by zimzaza4** [comment]
This problem still exists

**Comment by Seggan** [comment]
This has definitely been fixed in later versions. We have received reports earlier, fixed it, and we have  no more reports.
