### ISSUE TITLE
Free Diamond Anvil Cells

### ISSUE THREAD

**Issue by AN0NISN4P** [Slimefun-Addon-Community/Galactifun#86]
## Description (Required)
From the Slimefun Guide, you can grab the Diamond Anvil Cell from the Assembly Table Recipes page. 
[like this](https://gyazo.com/8b35866b90e33e74d986abaf25d2ac5b)

## Steps to reproduce the Issue (Required)
1. Open Slimefun Guide
2. Navigate to Assembly Table Recipes
3. Click on Diamond Anvil Cell
4. Exit the menu

## Expected behavior (Required)
When clicking the Diamond Anvil Cell the recipe should show, it doesn't.

## Environment (Required)
[Server Information](https://gyazo.com/7e093f2ebedd347e863db0a20f286ad2)
[Galactifun Version](https://gyazo.com/8ba7f0fd0d8734ee6621459e9d802ed2)

**Comment by Seggan** [comment]
Update to latest
