### ISSUE TITLE
Custom Mobs do not spawn. End Chunks Generating instead of Moon Chunks.

### ISSUE THREAD

**Issue by NickReagan** [Slimefun-Addon-Community/Galactifun#93]
Custom Mobs do not spawn. End chunks generate after 25~ chunks from the drop point on the moon. Screenshots attached.
![image](https://user-images.githubusercontent.com/52389274/140201644-57094013-1430-4c98-aae9-08590e78d639.png)
![image](https://user-images.githubusercontent.com/52389274/140204970-75b95918-6f39-44a3-8fe8-69e3a52adac0.png)
![image](https://user-images.githubusercontent.com/52389274/140205125-175721d8-374d-41fc-96e8-120f605262e1.png)
![image](https://user-images.githubusercontent.com/52389274/140205407-8cebe5cd-48f2-4cdd-8cc6-2b9fb78a9e8b.png)
![image](https://user-images.githubusercontent.com/52389274/140216382-2b5d3300-bfa3-4ef8-8624-bf974ade3377.png)

No console errors.

Paper Version;
1.17.1-359

SF Version ; 
DEV 984 (git 82978)

GF Version;
DEV 24 (git 30127)
 
 If yall need more info just ask.

**Comment by Seggan** [comment]
Resolved on Discord
